```{r}
devtools::install_github('https://github.com/paulvanderlaken/ppsr')
library("ppsr")
```

```{r}
MetaData_PPS <- select(MetaData, c("Age","Gender","Tissue.Type","Tumor.Location","Lauren.Classification","T","N","M","G","Stage","Survival","Mucin.Phenotype","MUC1","MUC5AC","MUC6","MUC2","MUC4","MUC13"))

MetaData_PPS$Tumor.Location[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$Lauren.Classification[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$T[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$N[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$M[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$G[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$Stage[MetaData_PPS$Tissue.Type == "adjacent"] <- NA
MetaData_PPS$Mucin.Phenotype[MetaData_PPS$Tissue.Type == "adjacent"] <- NA

MetaData_PPS <- subset(MetaData_PPS, Tissue.Type != "noninflammed")
MetaData_PPS <- droplevels(MetaData_PPS,Tissue.Type = "noninflammed")

MetaData_PPS$T <- as.factor(MetaData_PPS$T)
MetaData_PPS$N <- as.factor(MetaData_PPS$N)
MetaData_PPS$M <- as.factor(MetaData_PPS$M)
MetaData_PPS$G <- as.factor(MetaData_PPS$G)
MetaData_PPS$Stage <- as.factor(MetaData_PPS$Stage)


PPS_df <- score_df(MetaData_PPS)
HeatMap_pps <- visualize_pps(MetaData_PPS,color_value_low = "white", color_value_high = "#7A0403", color_text = "black")
```

